remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

color_scheme: "dark"
search_enabled: true

include:
  - index.md
  - 2_github_configuration.md
  - 3_github_content.md
  - 4_instalation_browxy.md
  - 5_instalation_local_dev.md
